package pojos;
// Generated 22-may-2022 19:11:40 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Bilhete generated by hbm2java
 */
public class Bilhete  implements java.io.Serializable {


     private Integer id;
     private Iva iva;
     private Tipo tipo;
     private String nome;
     private Date dataCriacao;
     private double valor;
     private int quantidade;
     private Set<SolicitudeBilhete> solicitudeBilhetes = new HashSet<SolicitudeBilhete>(0);

    public Bilhete() {
    }

	
    public Bilhete(Tipo tipo, String nome, Date dataCriacao, double valor, int quantidade) {
        this.tipo = tipo;
        this.nome = nome;
        this.dataCriacao = dataCriacao;
        this.valor = valor;
        this.quantidade = quantidade;
    }
    public Bilhete(Iva iva, Tipo tipo, String nome, Date dataCriacao, double valor, int quantidade, Set<SolicitudeBilhete> solicitudeBilhetes) {
       this.iva = iva;
       this.tipo = tipo;
       this.nome = nome;
       this.dataCriacao = dataCriacao;
       this.valor = valor;
       this.quantidade = quantidade;
       this.solicitudeBilhetes = solicitudeBilhetes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Iva getIva() {
        return this.iva;
    }
    
    public void setIva(Iva iva) {
        this.iva = iva;
    }
    public Tipo getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Tipo tipo) {
        this.tipo = tipo;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Date getDataCriacao() {
        return this.dataCriacao;
    }
    
    public void setDataCriacao(Date dataCriacao) {
        this.dataCriacao = dataCriacao;
    }
    public double getValor() {
        return this.valor;
    }
    
    public void setValor(double valor) {
        this.valor = valor;
    }
    public int getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(int quantidade) {
        this.quantidade = quantidade;
    }
    public Set<SolicitudeBilhete> getSolicitudeBilhetes() {
        return this.solicitudeBilhetes;
    }
    
    public void setSolicitudeBilhetes(Set<SolicitudeBilhete> solicitudeBilhetes) {
        this.solicitudeBilhetes = solicitudeBilhetes;
    }




}


