package pojos;
// Generated 29-abr-2022 10:39:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EstudoFactibilidade generated by hbm2java
 */
public class EstudoFactibilidade  implements java.io.Serializable {


     private Integer id;
     private String nomeProjeto;
     private String descricao;
     private String enfoque;
     private String resultadoEsperado;
     private double costo;
     private Set<Servico> servicos = new HashSet<Servico>(0);

    public EstudoFactibilidade() {
    }

	
    public EstudoFactibilidade(String nomeProjeto, String descricao, String resultadoEsperado, double costo) {
        this.nomeProjeto = nomeProjeto;
        this.descricao = descricao;
        this.resultadoEsperado = resultadoEsperado;
        this.costo = costo;
    }
    public EstudoFactibilidade(String nomeProjeto, String descricao, String enfoque, String resultadoEsperado, double costo, Set<Servico> servicos) {
       this.nomeProjeto = nomeProjeto;
       this.descricao = descricao;
       this.enfoque = enfoque;
       this.resultadoEsperado = resultadoEsperado;
       this.costo = costo;
       this.servicos = servicos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNomeProjeto() {
        return this.nomeProjeto;
    }
    
    public void setNomeProjeto(String nomeProjeto) {
        this.nomeProjeto = nomeProjeto;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public String getEnfoque() {
        return this.enfoque;
    }
    
    public void setEnfoque(String enfoque) {
        this.enfoque = enfoque;
    }
    public String getResultadoEsperado() {
        return this.resultadoEsperado;
    }
    
    public void setResultadoEsperado(String resultadoEsperado) {
        this.resultadoEsperado = resultadoEsperado;
    }
    public double getCosto() {
        return this.costo;
    }
    
    public void setCosto(double costo) {
        this.costo = costo;
    }
    public Set<Servico> getServicos() {
        return this.servicos;
    }
    
    public void setServicos(Set<Servico> servicos) {
        this.servicos = servicos;
    }




}


