package pojos;
// Generated 22-may-2022 19:11:40 by Hibernate Tools 4.3.1



/**
 * EstudoFactibilidade generated by hbm2java
 */
public class EstudoFactibilidade  implements java.io.Serializable {


     private Integer id;
     private String nomeProjeto;
     private String descricao;
     private String enfoque;
     private String resultadoEsperado;
     private double costo;

    public EstudoFactibilidade() {
    }

	
    public EstudoFactibilidade(String nomeProjeto, String descricao, String resultadoEsperado, double costo) {
        this.nomeProjeto = nomeProjeto;
        this.descricao = descricao;
        this.resultadoEsperado = resultadoEsperado;
        this.costo = costo;
    }
    public EstudoFactibilidade(String nomeProjeto, String descricao, String enfoque, String resultadoEsperado, double costo) {
       this.nomeProjeto = nomeProjeto;
       this.descricao = descricao;
       this.enfoque = enfoque;
       this.resultadoEsperado = resultadoEsperado;
       this.costo = costo;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNomeProjeto() {
        return this.nomeProjeto;
    }
    
    public void setNomeProjeto(String nomeProjeto) {
        this.nomeProjeto = nomeProjeto;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public String getEnfoque() {
        return this.enfoque;
    }
    
    public void setEnfoque(String enfoque) {
        this.enfoque = enfoque;
    }
    public String getResultadoEsperado() {
        return this.resultadoEsperado;
    }
    
    public void setResultadoEsperado(String resultadoEsperado) {
        this.resultadoEsperado = resultadoEsperado;
    }
    public double getCosto() {
        return this.costo;
    }
    
    public void setCosto(double costo) {
        this.costo = costo;
    }




}


