package pojos;
// Generated 22-may-2022 19:11:40 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Iva generated by hbm2java
 */
public class Iva  implements java.io.Serializable {


     private Integer id;
     private double porcetagem;
     private Set<Bilhete> bilhetes = new HashSet<Bilhete>(0);

    public Iva() {
    }

	
    public Iva(double porcetagem) {
        this.porcetagem = porcetagem;
    }
    public Iva(double porcetagem, Set<Bilhete> bilhetes) {
       this.porcetagem = porcetagem;
       this.bilhetes = bilhetes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public double getPorcetagem() {
        return this.porcetagem;
    }
    
    public void setPorcetagem(double porcetagem) {
        this.porcetagem = porcetagem;
    }
    public Set<Bilhete> getBilhetes() {
        return this.bilhetes;
    }
    
    public void setBilhetes(Set<Bilhete> bilhetes) {
        this.bilhetes = bilhetes;
    }




}


