package pojos;
// Generated 22-may-2022 19:11:40 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * MetodoPagamento generated by hbm2java
 */
public class MetodoPagamento  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private Set<Venda> vendas = new HashSet<Venda>(0);

    public MetodoPagamento() {
    }

	
    public MetodoPagamento(String nome) {
        this.nome = nome;
    }
    public MetodoPagamento(String nome, Set<Venda> vendas) {
       this.nome = nome;
       this.vendas = vendas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set<Venda> getVendas() {
        return this.vendas;
    }
    
    public void setVendas(Set<Venda> vendas) {
        this.vendas = vendas;
    }




}


