package pojos;
// Generated 29-abr-2022 10:39:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Provincia generated by hbm2java
 */
public class Provincia  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private Set<Municipio> municipios = new HashSet<Municipio>(0);

    public Provincia() {
    }

	
    public Provincia(String nome) {
        this.nome = nome;
    }
    public Provincia(String nome, Set<Municipio> municipios) {
       this.nome = nome;
       this.municipios = municipios;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set<Municipio> getMunicipios() {
        return this.municipios;
    }
    
    public void setMunicipios(Set<Municipio> municipios) {
        this.municipios = municipios;
    }




}


