package pojos;
// Generated 29-abr-2022 10:39:04 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Servico generated by hbm2java
 */
public class Servico  implements java.io.Serializable {


     private Integer id;
     private EstudoFactibilidade estudoFactibilidade;
     private Iva iva;
     private TipoServico tipoServico;
     private String nome;
     private Date dataCriacao;
     private double valor;
     private String descricao;
     private Set<SolicitudeServico> solicitudeServicos = new HashSet<SolicitudeServico>(0);

    public Servico() {
    }

	
    public Servico(TipoServico tipoServico, String nome, Date dataCriacao, double valor, String descricao) {
        this.tipoServico = tipoServico;
        this.nome = nome;
        this.dataCriacao = dataCriacao;
        this.valor = valor;
        this.descricao = descricao;
    }
    public Servico(EstudoFactibilidade estudoFactibilidade, Iva iva, TipoServico tipoServico, String nome, Date dataCriacao, double valor, String descricao, Set<SolicitudeServico> solicitudeServicos) {
       this.estudoFactibilidade = estudoFactibilidade;
       this.iva = iva;
       this.tipoServico = tipoServico;
       this.nome = nome;
       this.dataCriacao = dataCriacao;
       this.valor = valor;
       this.descricao = descricao;
       this.solicitudeServicos = solicitudeServicos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public EstudoFactibilidade getEstudoFactibilidade() {
        return this.estudoFactibilidade;
    }
    
    public void setEstudoFactibilidade(EstudoFactibilidade estudoFactibilidade) {
        this.estudoFactibilidade = estudoFactibilidade;
    }
    public Iva getIva() {
        return this.iva;
    }
    
    public void setIva(Iva iva) {
        this.iva = iva;
    }
    public TipoServico getTipoServico() {
        return this.tipoServico;
    }
    
    public void setTipoServico(TipoServico tipoServico) {
        this.tipoServico = tipoServico;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Date getDataCriacao() {
        return this.dataCriacao;
    }
    
    public void setDataCriacao(Date dataCriacao) {
        this.dataCriacao = dataCriacao;
    }
    public double getValor() {
        return this.valor;
    }
    
    public void setValor(double valor) {
        this.valor = valor;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Set<SolicitudeServico> getSolicitudeServicos() {
        return this.solicitudeServicos;
    }
    
    public void setSolicitudeServicos(Set<SolicitudeServico> solicitudeServicos) {
        this.solicitudeServicos = solicitudeServicos;
    }




}


