package pojos;
// Generated 29-abr-2022 10:39:04 by Hibernate Tools 4.3.1



/**
 * SolicitudeServico generated by hbm2java
 */
public class SolicitudeServico  implements java.io.Serializable {


     private Integer id;
     private Servico servico;
     private Solicitude solicitude;
     private int quantidade;

    public SolicitudeServico() {
    }

    public SolicitudeServico(Servico servico, Solicitude solicitude, int quantidade) {
       this.servico = servico;
       this.solicitude = solicitude;
       this.quantidade = quantidade;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Servico getServico() {
        return this.servico;
    }
    
    public void setServico(Servico servico) {
        this.servico = servico;
    }
    public Solicitude getSolicitude() {
        return this.solicitude;
    }
    
    public void setSolicitude(Solicitude solicitude) {
        this.solicitude = solicitude;
    }
    public int getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(int quantidade) {
        this.quantidade = quantidade;
    }




}


