package pojos;
// Generated 29-abr-2022 10:39:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoServico generated by hbm2java
 */
public class TipoServico  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private Set<Servico> servicos = new HashSet<Servico>(0);

    public TipoServico() {
    }

	
    public TipoServico(String nome) {
        this.nome = nome;
    }
    public TipoServico(String nome, Set<Servico> servicos) {
       this.nome = nome;
       this.servicos = servicos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set<Servico> getServicos() {
        return this.servicos;
    }
    
    public void setServicos(Set<Servico> servicos) {
        this.servicos = servicos;
    }




}


