package pojos;
// Generated 29-abr-2022 10:39:04 by Hibernate Tools 4.3.1



/**
 * Venda generated by hbm2java
 */
public class Venda  implements java.io.Serializable {


     private Integer id;
     private Funcionario funcionario;
     private MetodoPagamento metodoPagamento;
     private Solicitude solicitude;
     private Float total;

    public Venda() {
    }

	
    public Venda(Funcionario funcionario, MetodoPagamento metodoPagamento, Solicitude solicitude) {
        this.funcionario = funcionario;
        this.metodoPagamento = metodoPagamento;
        this.solicitude = solicitude;
    }
    public Venda(Funcionario funcionario, MetodoPagamento metodoPagamento, Solicitude solicitude, Float total) {
       this.funcionario = funcionario;
       this.metodoPagamento = metodoPagamento;
       this.solicitude = solicitude;
       this.total = total;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public MetodoPagamento getMetodoPagamento() {
        return this.metodoPagamento;
    }
    
    public void setMetodoPagamento(MetodoPagamento metodoPagamento) {
        this.metodoPagamento = metodoPagamento;
    }
    public Solicitude getSolicitude() {
        return this.solicitude;
    }
    
    public void setSolicitude(Solicitude solicitude) {
        this.solicitude = solicitude;
    }
    public Float getTotal() {
        return this.total;
    }
    
    public void setTotal(Float total) {
        this.total = total;
    }




}


